version: '3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  redis:
    image: redis:alpine


  celery:
    build: .
    command: celery -A backend_highload worker --loglevel=info
    depends_on:
      - redis
